name: "Coverage"

on:
  pull_request:

  push:
    branches: ["*"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  coverage:
    name: "Phpunit"
    uses: contributte/.github/.github/workflows/phpunit-coverage.yml@v1
    with:
      make: "init coverage"
