name: "Node"

on:
  pull_request:
  push:
    branches:
      - "master"
  schedule:
    - cron: "0 8 * * 1" # At 08:00 on Monday

jobs:
  webpack:
    name: "Webpack Build"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Use Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm run build
